Repository celestiaorg/celestia-core, pull requests merged in 2022-08, with the labels that each got.

#802 Backport v0.35.x changes to v0.34.x
  .github/dependabot.yml
  README.md
  blockchain/msgs_test.go
  blockchain/v0/reactor_test.go
  blockchain/v1/peer_test.go
  blockchain/v1/pool_test.go
  blockchain/v1/reactor_fsm_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/replay_test.go
  docs/celestia-architecture/README.md
  docs/celestia-architecture/adr-001-block-propagation.md
  docs/celestia-architecture/adr-002-ipld-da-sampling.md
  docs/celestia-architecture/adr-003-application-data-retrieval.md
  docs/celestia-architecture/adr-004-mvp-light-client.md
  docs/celestia-architecture/adr-005-decouple-blockid-and-partsetheader.md
  docs/celestia-architecture/adr-006-row-propagation.md
  docs/celestia-architecture/adr-007-minimal-changes-to-tendermint.md
  docs/celestia-architecture/adr-008-updating-to-tendermint-v0.35.x.md
  docs/celestia-architecture/adr-template.md
  docs/celestia-architecture/assets/user-request.png
  docs/celestia-architecture/celestia-logo.png
  docs/celestia-architecture/img/core-node-relation.jpg
  docs/celestia-architecture/img/extended_square.png
  evidence/pool_test.go
  go.mod
  go.sum
  mempool/v1/mempool.go
  mempool/v1/mempool_test.go
  pkg/da/data_availability_header.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  rpc/core/tx.go
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state.go
  state/test/factory/block.go
  state/validation_test.go
  store/store_test.go
  test/factory/tx.go
  types/block.go
  types/block_test.go
  types/event_bus_test.go
  types/shares_test.go
  types/test_util.go
  types/tx.go
  types/tx_test.go
Labels: C: core/app

#838 Use begin end/block instead of query in data commitments
  light/proxy/routes.go
  light/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mock/client.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/routes.go
Labels: quantum gravity bridge

#819 feat: add share index to malleated (wrapped) txs
  mempool/v0/clist_mempool.go
  mempool/v1/mempool.go
  mempool/v1/mempool_test.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  state/execution.go
  types/tx.go
  types/tx_test.go
Labels: C: core/app

#845 Fix golangci config warning
  .github/workflows/lint.yml
Labels: C:CI
