Repository celestiaorg/celestia-core, pull requests merged in 2022-09, with the labels that each got.

#850 Delete share and `TxInclusion` code
  blockchain/msgs_test.go
  pkg/prove/proof.go
  pkg/prove/proof_test.go
  rpc/client/rpc_test.go
  rpc/core/tx.go
  state/validation_test.go
  types/block.go
  types/block_test.go
  types/share_merging.go
  types/share_splitting.go
  types/shares.go
  types/shares_test.go
  types/tx.go
Labels: breaking

#859 feat!: Use a custom ABCI query to prove transaction inclusion
  pkg/consts/consts.go
  rpc/core/tx.go
Labels: C:abci, C: core/app

#860 chore!: delete remaining packages that have been moved to the app
  pkg/da/data_availability_header.go
  pkg/da/data_availability_header_test.go
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: C: core/app, breaking

#861 breaking!: move share consts to celestia-app
  pkg/consts/consts.go
Labels: breaking

#855 chore!: Rename OriginalSquareSize to SquareSize so that same name to same thing.
  proto/tendermint/abci/types.proto
  proto/tendermint/consensus/types.pb.go
  proto/tendermint/consensus/types.proto
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  types/block.go
Labels: breaking
