Repository celestiaorg/celestia-core, pull requests merged in 2022-04, with the labels that each got.

#676 force linter to use go 1.17
  .github/workflows/lint.yaml
Labels: C:CI

#699 Fix codeowners
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: T:chore

#706 fix the wrapping directive causing some tests to fail
  crypto/xchacha20poly1305/xchachapoly_test.go
Labels: T:Bug, T:chore

#700 pull remaining changes from master to v0.34.x-celestia
  .github/workflows/linter.yml
  docs/architecture/README.md
  pkg/wrapper/nmt_wrapper.go
  pkg/wrapper/nmt_wrapper_test.go
Labels: T:chore

#710 Change CI to work on pushes to default branch instead of master.
  .github/workflows/coverage.yml
  .github/workflows/docker.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yaml
  .github/workflows/linter.yml
  .github/workflows/proto-docker.yml
  .github/workflows/tests.yml
Labels: C:CI

#709 Remove check rule from makefile.
  Makefile
Labels: T:chore

#712 Remove push from Build & Push ci
  .github/workflows/docker.yml
Labels: C:CI, C:tendermint-modifications

#713 Fix super linter CI
  .github/workflows/linter.yml
  docs/architecture/README.md
Labels: C:CI

#714 Temporarily disable socket client app test
  .github/workflows/tests.yml
  abci/client/socket_client.go
  abci/server/socket_server.go
Labels: C:CI, T:tests

#716 Fix proto breakage URL.
  Makefile
Labels: T:Bug, C:CI

#715 bug: temporary fix until we update to tendermint 0.35
  rpc/core/events.go
Labels: T:Bug

#723 remove ISRs for now
  blockchain/msgs_test.go
  blockchain/v0/reactor_test.go
  blockchain/v1/peer_test.go
  blockchain/v1/pool_test.go
  blockchain/v1/reactor_fsm_test.go
  blockchain/v1/reactor_test.go
  blockchain/v2/reactor_test.go
  consensus/replay_test.go
  evidence/pool_test.go
  pkg/consts/consts.go
  pkg/prove/proof.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state.go
  state/test/factory/block.go
  state/tx_filter_test.go
  state/validation_test.go
  store/store_test.go
  types/block.go
  types/block_test.go
  types/event_bus_test.go
  types/share_merging.go
  types/share_splitting.go
  types/shares_test.go
  types/tx_test.go
Labels: C:types

#726 update rsmt2d 03.1 -> 0.4.0
  .github/workflows/coverage.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-master.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  Makefile
  go.mod
  go.sum
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: T:dependencies
