Repository celestiaorg/celestia-core, pull requests merged in 2022-07, with the labels that each got.

#798 Fix image file extension
  docs/celestia-architecture/adr-007-minimal-changes-to-tendermint.md
Labels: C:documentation

#794 Configure dependabot to only check for Celestia deps.
  .github/dependabot.yml
Labels: T:dependencies, C:CI

#796 fix: links on celestia-architecture README
  docs/celestia-architecture/README.md
Labels: C:documentation, T:chore
