Repository celestiaorg/celestia-core, pull requests merged in 2023-08, with the labels that each got.

#1055 feat: Add standard tracing points to portions of the mempool and consensus
  config/config.go
  config/toml.go
  consensus/reactor.go
  consensus/state.go
  mempool/cat/reactor.go
  mempool/v1/reactor.go
  mempool/v1/reactor_test.go
  node/node.go
  pkg/trace/README.md
  pkg/trace/client.go
  pkg/trace/doc.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/mempool.go
  pkg/trace/schema/tables.go
  test/maverick/node/node.go
Labels: introspection

#1057 fix: pass configured tables to the trace client
  pkg/trace/client.go
Labels: T:Bug, introspection

#1058 fix: end exclusive data commitment range fix
  rpc/core/blocks.go
  rpc/core/blocks_test.go
Labels: quantum gravity bridge

#1060 fix: end exclusive data commitment range fix (#1058)
  rpc/core/blocks.go
  rpc/core/blocks_test.go
Labels: quantum gravity bridge

#1051 feat!: remove square size from block data
  abci/types/application.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  state/execution.go
  types/block.go
Labels: C:types, breaking
