Repository celestiaorg/celestia-core, pull requests merged in 2023-04, with the labels that each got.

#999 docs: document data root tuple hex representation padding
  rpc/core/blocks.go
Labels: C:documentation

#1001 feat: commit to original square size in data commitments
  rpc/core/blocks.go
  rpc/core/blocks_test.go
Labels: quantum gravity bridge, breaking

#1002 fix: register EventDataSignedBlock in tendermint's json lib
  types/events.go
Labels: T:Bug
