Repository celestiaorg/celestia-core, pull requests merged in 2023-03, with the labels that each got.

#975 ci: fix proto-gen failing workflow
  .github/workflows/check-generated.yml
  Makefile
Labels: C:CI

#969 feat!: increase tx namespace id to 32 bytes
  mempool/cat/pool_test.go
  mempool/v0/clist_mempool_test.go
  mempool/v1/mempool_test.go
  pkg/consts/consts.go
  types/tx.go
  types/tx_test.go
Labels: breaking

#970 feat: add influxdb trace collection
  cmd/tendermint/commands/run_node.go
  config/config.go
  config/toml.go
  consensus/state.go
  go.mod
  go.sum
  node/node.go
  pkg/trace/README.md
  pkg/trace/client.go
  pkg/trace/doc.go
  pkg/trace/flags.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
  test/e2e/runner/setup.go
  test/e2e/runner/start.go
Labels: T:devops, introspection

#984 fix: add an extra check when the data commitment first block is 0
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
Labels: T:Bug

#985 feat!: versioned namespaces
  mempool/cat/pool_test.go
  mempool/v0/clist_mempool_test.go
  mempool/v1/mempool_test.go
  pkg/consts/consts.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  types/block.go
  types/block_test.go
  types/row_proof_test.go
  types/share_proof.go
  types/share_proof_test.go
  types/tx.go
  types/tx_test.go
Labels: breaking

#987 feat!: versioned namespaces
  mempool/cat/pool_test.go
  mempool/v0/clist_mempool_test.go
  mempool/v1/mempool_test.go
  pkg/consts/consts.go
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  types/block.go
  types/block_test.go
  types/row_proof_test.go
  types/share_proof.go
  types/share_proof_test.go
  types/tx.go
  types/tx_test.go
Labels: breaking

#988 chore!: remove `BlobFromProto` and `BlobsFromProto`
  types/block.go
Labels: breaking
