Repository celestiaorg/celestia-core, pull requests merged in 2024-06, with the labels that each got.

#1340 fix!: trace file seeking
  pkg/trace/buffered_file.go
  pkg/trace/fileserver.go
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
  pkg/trace/tracer.go
Labels: WS: Big Blonks 🔭, fix

#1374 feat: enhances S3Download to filter by traced table names
  pkg/trace/fileserver.go
Labels: S:backport-to-v0.34.x, feature

#1379 chore: bumps go version to 1.22.4 in v0.34.x-celestia
  DOCKER/Dockerfile
  README.md
  go.mod
  scripts/proto-gen.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: WS: Maintenance 🔧

#1287 feat: add tx status in mempool
  consensus/replay_stubs.go
  go.mod
  go.sum
  mempool/cache.go
  mempool/cat/pool.go
  mempool/cat/pool_test.go
  mempool/cat/reactor.go
  mempool/cat/store.go
  mempool/mempool.go
  mempool/mock/mempool.go
  mempool/v0/clist_mempool.go
  mempool/v0/clist_mempool_test.go
  mempool/v1/mempool.go
  mempool/v1/mempool_test.go
  rpc/client/rpc_test.go
  rpc/core/blocks.go
  rpc/core/blocks_test.go
  rpc/core/mocks/mempool.go
  rpc/core/tx.go
  rpc/core/tx_status_test.go
  rpc/core/types/responses.go
  state/mocks/block_store.go
  test/maverick/consensus/replay_stubs.go
Labels: WS: BestTxs

#1401 chore: adds logs for the state of the trace pull server
  pkg/trace/fileserver.go
  pkg/trace/local_tracer.go
Labels: WS: Big Blonks 🔭
