Repository celestiaorg/celestia-core, pull requests merged in 2024-02, with the labels that each got.

#1204 feat!: traces gossiped votes in the InfluxDB
  consensus/reactor.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/tables.go
Labels: S:backport-to-v0.34.x, WS: Big Blonks 🔭

#1212 chore: add more CODEOWNERS
  .github/CODEOWNERS
Labels: S:backport-to-v0.34.x

#1215 fix: correctly prune peers from the seenTxSet when disconnecting
  mempool/cat/cache.go
  mempool/cat/cache_test.go
  mempool/cat/reactor.go
  mempool/cat/reactor_test.go
  mempool/cat/requests.go
Labels: S:backport-to-v0.34.x

#1195 feat(mempool): add metric size of pool in bytes
  mempool/cat/pool.go
  mempool/metrics.go
  mempool/v0/clist_mempool.go
  mempool/v1/mempool.go
Labels: S:backport-to-v0.34.x

#1216 feat: add more consensus metrics on rejected proposals
  consensus/metrics.go
  consensus/state.go
Labels: S:backport-to-v0.34.x

#1199 test: messages surpassing MConnection's receiving buffer capacity are dropped
  p2p/conn/connection_bench_test.go
Labels: WS: Big Blonks 🔭

#1227 fix: use genesis file app version if it is set
  consensus/replay.go
  state/state.go
  state/state_test.go
Labels: S:backport-to-v0.34.x

#1244 Update Pyroscope Dependencies for Go 1.22 Compiler Compatibility
  go.mod
  go.sum
  node/tracing.go
Labels: S:backport-to-v0.34.x
