Repository celestiaorg/celestia-core, pull requests merged in 2024-05, with the labels that each got.

#1330 docs: update the openapi specs to contain the share proof
  rpc/openapi/openapi.yaml
Labels: C:documentation, blobstream

#1326 feat: support writing only internal messages to WAL
  config/config.go
  config/toml.go
  consensus/state.go
Labels: C:consensus

#1321 test(mempool/cat): fix flaky TestTxPool_BroadcastQueue
  mempool/cat/pool_test.go
Labels: S:backport-to-v0.34.x

#1343 docs: add the prove shares endpoint to openapi specs
  rpc/openapi/openapi.yaml
Labels: C:documentation

#1348 chore(deps): bump go to v1.22.3
  .github/workflows/check-generated.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  README.md
  go.mod
  scripts/proto-gen.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: T:chore

#1347 chore(deps): bump go to v1.22.3
  DOCKER/Dockerfile
  README.md
  go.mod
  scripts/proto-gen.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: T:chore

#1351 feat: wrap ShareProof in a ResultShareProof
  light/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/core/routes.go
  rpc/core/tx.go
  rpc/core/types/responses.go
  rpc/openapi/openapi.yaml
Labels: blobstream

#1353 chore: increase the data commitment blocks limit in the API (Backport #1268)
  pkg/consts/consts.go
  rpc/core/blocks.go
Labels: blobstream

#1354 docs: go doc feedback for PR #1351
  light/rpc/client.go
Labels: C:documentation

#1327 chore: extract buf version
  Makefile
Labels: S:backport-to-v0.34.x

#1295 feat: add tracing for remaining consensus messages, peer updates, and abci calls
  consensus/reactor.go
  consensus/state.go
  mempool/cat/reactor.go
  mempool/v1/reactor.go
  node/node.go
  p2p/peer.go
  p2p/switch.go
  p2p/test_util.go
  p2p/transport.go
  p2p/transport_test.go
  pkg/trace/buffered_file.go
  pkg/trace/fileserver.go
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/mempool.go
  pkg/trace/schema/misc.go
  pkg/trace/schema/p2p.go
  pkg/trace/schema/schema.go
  pkg/trace/tracer.go
  test/maverick/node/node.go
Labels: WS: Big Blonks 🔭, backport
