Repository celestiaorg/celestia-core, pull requests merged in 2024-01, with the labels that each got.

#1158 feat: more precise mempool metrics
  mempool/metrics.go
  mempool/v1/mempool.go
  node/node.go
  pkg/trace/schema/mempool.go
Labels: introspection

#1160 fix: catch context errors from http provider
  light/provider/http/http.go
  light/provider/http/http_test.go
Labels: S:backport-to-v0.34.x

#1159 feat: more precise metrics
  Makefile
  mempool/metrics.go
  mempool/v1/mempool.go
  node/node.go
  pkg/trace/schema/mempool.go
Labels: introspection

#1170 fix: make priority calculations consistent for TestTxMempool_ReapMaxBytes
  mempool/cat/pool_test.go
  mempool/v1/mempool_test.go
Labels: S:backport-to-v0.34.x, fix

#1174 feat: add MaxGossipDelay from CAT pool to the config
  config/config.go
  config/toml.go
  mempool/cat/reactor.go
  node/node.go
  test/maverick/node/node.go
Labels: S:backport-to-v0.34.x

#1176 test: MConnection benchmark
  libs/log/testing_logger.go
  p2p/conn/connection_test.go
Labels: testing, block prop, WS: Big Blonks 🔭

#1179 test: Benchmark MConnection with large size messages
  p2p/conn/connection_test.go
Labels: testing, WS: Big Blonks 🔭

#1189 test: channel ID impact on max bandwidth utilization in MConnection
  p2p/conn/connection_bench_test.go
Labels: testing, WS: Big Blonks 🔭

#1193 test: sequential receipt of messages in MConnection
  p2p/conn/connection_bench_test.go
Labels: WS: Big Blonks 🔭
