Repository celestiaorg/celestia-core, pull requests merged in 2024-04, with the labels that each got.

#1283 chore: go vuln
  .github/workflows/check-generated.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  README.md
  go.mod
  go.sum
  scripts/proto-gen.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: T:dependencies, S:backport-to-v0.34.x

#1284 feat: add the pull based fileserver
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  go.mod
  go.sum
  pkg/trace/README.md
  pkg/trace/decoder.go
  pkg/trace/fileserver.go
  pkg/trace/flags.go
  pkg/trace/local_client_test.go
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
  pkg/trace/tracer.go
  test/e2e/node/main.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
Labels: introspection, WS: Big Blonks 🔭

#1279 feat!: replace the influx trace client with the local trace client
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  consensus/reactor.go
  consensus/state.go
  go.mod
  go.sum
  mempool/cat/reactor.go
  mempool/v1/mempool.go
  mempool/v1/reactor.go
  mempool/v1/reactor_test.go
  node/node.go
  pkg/trace/README.md
  pkg/trace/buffered_file.go
  pkg/trace/client.go
  pkg/trace/decoder.go
  pkg/trace/doc.go
  pkg/trace/fileserver.go
  pkg/trace/flags.go
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/mempool.go
  pkg/trace/schema/schema.go
  pkg/trace/schema/schema_test.go
  pkg/trace/schema/tables.go
  pkg/trace/tracer.go
  test/e2e/node/main.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
  test/maverick/node/node.go
Labels: WS: Big Blonks 🔭

#1294 chore: delete security policy to use github's default
  SECURITY.md
Labels: S:backport-to-v0.34.x

#1290 feat!: replace the influx tracer with a local one
  .golangci.yml
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  consensus/reactor.go
  consensus/state.go
  go.mod
  go.sum
  mempool/cat/reactor.go
  mempool/v1/mempool.go
  mempool/v1/reactor.go
  mempool/v1/reactor_test.go
  node/node.go
  pkg/trace/README.md
  pkg/trace/buffered_file.go
  pkg/trace/client.go
  pkg/trace/decoder.go
  pkg/trace/doc.go
  pkg/trace/fileserver.go
  pkg/trace/flags.go
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/mempool.go
  pkg/trace/schema/schema.go
  pkg/trace/schema/schema_test.go
  pkg/trace/schema/tables.go
  pkg/trace/tracer.go
  test/e2e/node/main.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
  test/maverick/node/node.go
Labels: backport

#1312 fix: downgrade viper
  go.mod
  go.sum
Labels: T:Bug

#1313 feat!: wrap ShareProof in ResultShareProof
  light/rpc/client.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/core/tx.go
  rpc/core/types/responses.go
Labels: C:rpc, breaking, blobstream, WS: v2 :v:

#1292 feat: add tracing for remaining consensus messages, abci calls, and peer updates
  consensus/reactor.go
  consensus/state.go
  mempool/cat/reactor.go
  mempool/v1/reactor.go
  node/node.go
  p2p/peer.go
  p2p/switch.go
  p2p/test_util.go
  p2p/transport.go
  p2p/transport_test.go
  pkg/trace/fileserver.go
  pkg/trace/local_tracer.go
  pkg/trace/schema/consensus.go
  pkg/trace/schema/mempool.go
  pkg/trace/schema/misc.go
  pkg/trace/schema/p2p.go
  pkg/trace/schema/schema.go
  test/maverick/node/node.go
Labels: introspection, WS: Big Blonks 🔭

#1319 feat: adds the feature to read push config from env vars (backport #1318)
  pkg/trace/README.md
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
Labels: WS: Big Blonks 🔭

#1318 feat: adds the feature to read push config from env vars
  pkg/trace/README.md
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
Labels: WS: Big Blonks 🔭

#1323 chore: introduces constants for tracer push configs environment variable names (manual backport #1324)
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
Labels: WS: Big Blonks 🔭

#1324 chore: introduces constants for tracer push configs environment variable names
  pkg/trace/local_tracer.go
  pkg/trace/local_tracer_test.go
Labels: WS: Big Blonks 🔭
