Repository celestiaorg/celestia-core, pull requests merged in 2025-07, with the labels that each got.

#1838 feat: simplify caching and expose rejected txs in TxStatus
  consensus/replay_stubs.go
  mempool/cache.go
  mempool/cache_bench_test.go
  mempool/cache_test.go
  mempool/cat/cache.go
  mempool/cat/cache_test.go
  mempool/cat/pool.go
  mempool/cat/pool_test.go
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/mempool.go
  mempool/mocks/mempool.go
  mempool/nop_mempool.go
  mempool/priority/mempool.go
  mempool/priority/mempool_test.go
  rpc/core/tx.go
  scripts/mockery_generate.sh
Labels: WS: BestTxs

#2121 chore: change "Failed to load block meta" catchup log to debug
  consensus/reactor.go
Labels: logging, WS: Maintenance 🔧

#2143 fix: adjust PEX request interval to match specification (backport #2140)
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: pex

#2157 chore: trace prepare proposal
  node/node.go
  state/execution.go
Labels: T:chore, low priority

#2158 chore:trace process proposal correctly
  consensus/state.go
Labels: T:chore

#2163 fix: correctly set the recovered mempool parts
  consensus/propagation/commitment.go
  consensus/propagation/types/combined_partset.go
Labels: recovery

#2165 feat: specify the number of needed parts
  consensus/propagation/catchup.go
  consensus/propagation/catchup_test.go
  consensus/propagation/have_wants.go
  consensus/propagation/have_wants_test.go
  consensus/propagation/peer_state.go
  consensus/propagation/types/types.go
  consensus/propagation/types/types_test.go
  proto/tendermint/propagation/types.pb.go
  proto/tendermint/propagation/types.proto
Labels: recovery

#2175 docs: explain Celestia-specific GRPC APIs
  README.md
Labels: backport-to-v0.38.x

#2183 chore: make received part for unknown proposal debug level
  consensus/propagation/have_wants.go
Labels: recovery

#2184 fix: make json decoding old v0.34 EventAttribute backwards compatible
  abci/types/types.go
  abci/types/types_test.go
Labels: backport-to-v0.38.x

#2215 fix: panic due to nil limit
  rpc/core/env.go
  rpc/core/env_test.go
  rpc/core/mempool.go
  rpc/core/mempool_test.go
Labels: backport-to-v0.34.x, backport-to-v0.38.x

#2202 feat: build the block pre-emptively during the commit timeout
  consensus/common_test.go
  consensus/state.go
Labels: C:consensus

#2246 chore: run the 50-50 compatibility test in CI
  .github/workflows/e2e.yml
  test/e2e/networks/propagation-reactor-compatibility.toml
Labels: WS: v5

#2245 fix: initialize peer state when proposing
  consensus/propagation/commitment.go
  consensus/propagation/have_wants.go
Labels: WS: v5

#2259 chore: send mempool recovered parts to consensus
  consensus/propagation/commitment.go
Labels: recovery

#2264 chore: only build the block pre-emptively when the timeout commit is high
  consensus/state.go
Labels: C:consensus
