Repository celestiaorg/celestia-core, pull requests merged in 2025-08, with the labels that each got.

#2269 chore: correctly initialise the new height channel
  consensus/state.go
Labels: recovery

#2288 fix: make the findNewPeerToRequestTx iterative
  mempool/cat/reactor.go
Labels: cat 🐈

#2294 chore: delete println
  state/txindex/kv/kv.go
Labels: WS: Maintenance 🔧

#2324 fix: use the timeout commit passed from the application to determine if
  consensus/state.go
Labels: WS: Big Blonks 🔭, WS: Maintenance 🔧, WS: v6

#2380 chore: bump nmt to v0.24.1
  go.mod
  go.sum
Labels: dependencies, 128mb/6s

#2386 fix: increase event bus buffer
  scripts/metricsgen/metricsgen.go
  types/event_bus.go
Labels: T:optimization, 128mb/6s, 128MB/3s, backport-to-v0.39.x
