Repository celestiaorg/celestia-core, pull requests merged in 2025-09, with the labels that each got.

#2382 feat: support delayed precommits
  config/config.go
  consensus/common_test.go
  consensus/state.go
  test/e2e/node/main.go
  types/event_bus.go
Labels: C:consensus, 128mb/6s, WS: v7

#2392 chore: update DelayedPrecommitTimeout docs and make its log debug level
  config/config.go
  consensus/state.go
Labels: C:documentation

#2387 fix!: stop panics in parallel reactor processing
  consensus/nil_vote_test.go
  consensus/propagation/have_wants.go
  p2p/base_reactor.go
  p2p/base_reactor_test.go
Labels: backport-to-v0.39.x

#2394 feat: store proposals with invalid signatures to the data/debug
  consensus/state.go
  types/utils.go
Labels: WS: v6

#2364 feat: dynamically change all timeouts using the application
  abci/example/kvstore/kvstore.go
  abci/types/types.pb.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/invalid_test.go
  consensus/mempool_test.go
  consensus/propagation/reactor.go
  consensus/replay.go
  consensus/state.go
  consensus/state_test.go
  node/node.go
  proto/tendermint/abci/types.proto
  proto/tendermint/propagation/types.proto
  proto/tendermint/rpc/grpc/types.proto
  proto/tendermint/state/types.pb.go
  proto/tendermint/state/types.proto
  proto/tendermint/types/validator.proto
  state/execution.go
  state/state.go
  state/state_test.go
  statesync/syncer.go
  test/e2e/app/app.go
  test/e2e/node/main.go
  types/part_set.go
Labels: WS: Big Blonks 🔭, WS: Maintenance 🔧, backport-to-main, WS: v6, 128mb/6s

#2435 perf: optimse create proposal block
  consensus/common_test.go
  internal/test/tx.go
  state/execution.go
  state/execution_test.go
  state/state.go
  state/store.go
  types/block.go
  types/marshalling.go
  types/marshalling_test.go
Labels: 128mb/6s, WS: v7, backport-to-v0.39.x

#2411 feat: only add the compact block after validating it and improve catchup
  consensus/propagation/catchup.go
  consensus/propagation/catchup_test.go
  consensus/propagation/commitment.go
  consensus/propagation/commitment_state.go
  consensus/propagation/commitment_state_test.go
  consensus/propagation/commitment_test.go
  consensus/propagation/have_want_test.go
  consensus/propagation/have_wants.go
  consensus/propagation/have_wants_test.go
  consensus/propagation/propagator.go
  consensus/propagation/reactor.go
  consensus/propagation/reactor_test.go
  consensus/reactor.go
  consensus/state.go
  test/e2e/status.sh
Labels: C:consensus, recovery, WS: v6, required, backport-to-v0.39.x

#2443 chore: improve error log
  consensus/propagation/types/types.go
Labels: low priority

#2466 fix: set MaxBlockSizeBytes to 128MiB
  consensus/reactor_test.go
  types/params.go
Labels: WS: v6, required

#2495 feat!: unlock the state before calling abci methods
  blocksync/reactor.go
  consensus/state.go
  libs/trace/schema/consensus.go
  state/execution.go
  state/execution_test.go
Labels: C:consensus, backport-to-v0.39.x
