Repository celestiaorg/celestia-core, pull requests merged in 2025-06, with the labels that each got.

#1945 fix: include proof in RecoveryPart messages when clearing wants
  consensus/propagation/have_wants.go
Labels: recovery, audit

#2026 chore: bump dockerfile go version to 1.24
  DOCKER/Dockerfile
  README.md
Labels: C:CI

#2055 chore: validate want parts size in handle wants
  consensus/propagation/have_wants.go
  consensus/propagation/types/combined_partset.go
Labels: recovery, audit

#2067 chore: only add recovered part if it's missing
  consensus/propagation/commitment.go
Labels: recovery

#2068 chore: improve channels lifecycle handling
  consensus/propagation/commitment.go
  consensus/propagation/have_wants.go
  consensus/propagation/peer_state.go
  consensus/propagation/peer_state_test.go
  consensus/propagation/reactor.go
Labels: recovery

#2070 fix: validate compact block data race
  consensus/propagation/commitment.go
Labels: recovery

#2105 docs(README): copy README from v0.34.x-celestia
  README.md
Labels: S:backport-to-v0.38.x

#2106 feat: more aggressive peer discovery (backport of #2029)
  p2p/pex/addrbook.go
  p2p/pex/addrbook_test.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: backport, ws: v4
