Repository celestiaorg/celestia-core, pull requests merged in 2025-10, with the labels that each got.

#2517 chore: remove unnecessary comments
  test/e2e/networks/propagation-reactor-compatibility.toml
Labels: C:documentation

#2522 fix: limit the number of SeenTx broadcast for new txs
  mempool/cat/reactor.go
Labels: WS: BestTxs

#2527 feat: limit the number of addresses in pex message
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: pex
